# - Locate photos library
# Defines:
#
#  STARLIGHT_FOUND
#  STARLIGHT_INCLUDE_DIR
#  STARLIGHT_INCLUDE_DIRS (not cached)
#  STARLIGHT_LIBRARY
#  STARLIGHT_LIBRARIES (not cached)


find_path(STARLIGHT_INCLUDE_DIR beam.h
          HINTS $ENV{STARLIGHT_ROOT_DIR}/include ${STARLIGHT_ROOT_DIR}/include)

find_library(STARLIGHT_LIBRARY NAMES Starlib
             HINTS $ENV{STARLIGHT_ROOT_DIR}/lib ${STARLIGHT_ROOT_DIR}/lib)

set(STARLIGHT_INCLUDE_DIRS ${STARLIGHT_INCLUDE_DIR})
set(STARLIGHT_LIBRARIES ${STARLIGHT_LIBRARY})

# handle the QUIETLY and REQUIRED arguments and set PHOTOS_FOUND to TRUE if
# all listed variables are TRUE

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(starlight DEFAULT_MSG STARLIGHT_INCLUDE_DIR STARLIGHT_LIBRARY)

mark_as_advanced(STARLIGHT_FOUND STARLIGHT_INCLUDE_DIR STARLIGHT_LIBRARY)
