# - Locate TINYXML library
# Defines:
#
#  TINYXML_FOUND
#  TINYXML_INCLUDE_DIR
#  TINYXML_INCLUDE_DIRS (not cached)
#  TINYXML_LIBRARY
#  TINYXML_LIBRARIES (not cached)

find_path(TINYXML_INCLUDE_DIR tinyxml.h)
find_library(TINYXML_LIBRARY NAMES tinyxml)

set(TINYXML_LIBRARIES ${TINYXML_LIBRARY})

set(TINYXML_INCLUDE_DIRS ${TINYXML_INCLUDE_DIR})

# handle the QUIETLY and REQUIRED arguments and set TINYXML_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TINYXML DEFAULT_MSG TINYXML_INCLUDE_DIR TINYXML_LIBRARIES)

mark_as_advanced(TINYXML_FOUND TINYXML_INCLUDE_DIR TINYXML_LIBRARY)
