# - Locate SIGCPP library
# Defines:
#
#  SIGCPP_FOUND
#  SIGCPP_INCLUDE_DIR
#  SIGCPP_INCLUDE_DIRS (not cached)
#  SIGCPP_LIBRARY
#  SIGCPP_CBLAS_LIBRARY
#  SIGCPP_LIBRARIES (not cached)

find_path(SIGCPP_INCLUDE_DIR sigc++/sigc++.h)
find_library(SIGCPP_LIBRARY NAMES sigc-2.0)

set(SIGCPP_LIBRARIES ${SIGCPP_LIBRARY})

set(SIGCPP_INCLUDE_DIRS ${SIGCPP_INCLUDE_DIR})

# handle the QUIETLY and REQUIRED arguments and set SIGCPP_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SIGCPP DEFAULT_MSG SIGCPP_INCLUDE_DIR SIGCPP_LIBRARIES)

mark_as_advanced(SIGCPP_FOUND SIGCPP_INCLUDE_DIR SIGCPP_LIBRARY)
