# - Locate TINYXML2 library
# Defines:
#
#  TINYXML2_FOUND
#  TINYXML2_INCLUDE_DIR
#  TINYXML2_INCLUDE_DIRS (not cached)
#  TINYXML2_LIBRARY
#  TINYXML2_LIBRARIES (not cached)

find_path(TINYXML2_INCLUDE_DIR tinyxml2.h)
find_library(TINYXML2_LIBRARY NAMES tinyxml2)

set(TINYXML2_LIBRARIES ${TINYXML2_LIBRARY})

set(TINYXML2_INCLUDE_DIRS ${TINYXML2_INCLUDE_DIR})

# handle the QUIETLY and REQUIRED arguments and set TINYXML2_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(TINYXML2 DEFAULT_MSG TINYXML2_INCLUDE_DIR TINYXML2_LIBRARIES)

mark_as_advanced(TINYXML2_FOUND TINYXML2_INCLUDE_DIR TINYXML2_LIBRARY)
