# - Locate hepMCanalysis library
# Defines:
#
#  HEPMCANALYSIS_FOUND
#  HEPMCANALYSIS_INCLUDE_DIR
#  HEPMCANALYSIS_LIBRARY
#  HEPMCANALYSIS_INCLUDE_DIRS (not cached)
#  HEPMCANALYSIS_LIBRARIES (not cached)

find_path(HEPMCANALYSIS_INCLUDE_DIR include/baseAnalysis.h
          HINTS $ENV{HEPMCANALYSIS_ROOT_DIR}/include/ ${HEPMCANALYSIS_ROOT_DIR}/include/)

find_library(HEPMCANALYSIS_LIBRARY NAMES HepMCAnalysis
             HINTS $ENV{HEPMCANALYSIS_ROOT_DIR}/lib ${HEPMCANALYSIS_ROOT_DIR}/lib)

set(HEPMCANALYSIS_INCLUDE_DIR ${HEPMCANALYSIS_ROOT_DIR}/include)
set(HEPMCANALYSIS_INCLUDE_DIRS ${HEPMCANALYSIS_INCLUDE_DIR})
set(HEPMCANALYSIS_LIBRARIES ${HEPMCANALYSIS_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Hepmcanalysis DEFAULT_MSG HEPMCANALYSIS_INCLUDE_DIR HEPMCANALYSIS_LIBRARY)

mark_as_advanced(HEPMCANALYSIS_FOUND HEPMCANALYSIS_INCLUDE_DIR HEPMCANALYSIS_LIBRARY)


