# - Locate lhapdf library
# Defines:
#
#  LHAPDF6_FOUND
#  LHAPDF6_INCLUDE_DIR
#  LHAPDF6_INCLUDE_DIRS (not cached)
#  LHAPDF6_LIBRARY
#  LHAPDF6_LIBRARIES (not cached)


find_path(LHAPDF6_INCLUDE_DIR LHAPDF/LHAPDF.h
          HINTS $ENV{LHAPDF6_ROOT_DIR}/include ${LHAPDF6_ROOT_DIR}/include)

find_library(LHAPDF6_LIBRARY NAMES LHAPDF
             HINTS $ENV{LHAPDF6_ROOT_DIR}/lib ${LHAPDF6_ROOT_DIR}/lib)

set(LHAPDF6_INCLUDE_DIRS ${LHAPDF6_INCLUDE_DIR})
set(LHAPDF6_LIBRARIES ${LHAPDF6_LIBRARY})

# handle the QUIETLY and REQUIRED arguments and set LHAPDF6_FOUND to TRUE if
# all listed variables are TRUE

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(lhapdf6 DEFAULT_MSG LHAPDF6_LIBRARY LHAPDF6_INCLUDE_DIR)

mark_as_advanced(LHAPDF6_FOUND LHAPDF6_LIBRARY LHAPDF6_INCLUDE_DIR)
