
find_library(TAUOLAPP_INTERFACE_LIBRARY NAMES TauolaCxxInterface 
             HINTS $ENV{TAUOLAPP_ROOT_DIR}/lib ${TAUOLAPP_ROOT_DIR}/lib)

find_library(TAUOLAPP_FORTRAN_LIBRARY NAMES TauolaFortran 
             HINTS $ENV{TAUOLAPP_ROOT_DIR}/lib ${TAUOLAPP_ROOT_DIR}/lib)

find_library(TAUOLAPP_TAUSPINNER_LIBRARY NAMES TauolaTauSpinner
             HINTS $ENV{TAUOLAPP_ROOT_DIR}/lib ${TAUOLAPP_ROOT_DIR}/lib)


set(TAUOLAPP_INCLUDE_DIR ${TAUOLAPP_ROOT_DIR}/include)
set(TAUOLAPP_INCLUDE_DIRS ${TAUOLAPP_INCLUDE_DIR})
set(TAUOLAPP_LIBRARIES ${TAUOLAPP_INTERFACE_LIBRARY} ${TAUOLAPP_FORTRAN_LIBRARY} ${TAUOLAPP_TAUSPINNER_LIBRARY})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Tauola++ DEFAULT_MSG TAUOLAPP_INCLUDE_DIR TAUOLAPP_LIBRARIES)

mark_as_advanced(TAUOLAPP_FOUND TAUOLAPP_INCLUDE_DIR TAUOLAPP_LIBRARIES)
